### ISSUE TITLE
Remove PT debug logs or set the hostname

### ISSUE THREAD

**Issue by Halama** [keboola/google-sheets-writer#10]
Zasekava to papertrail hromadou systemu, kazde spusteni ma jiny hostname (id kontejneru)
https://papertrailapp.com/destinations/6775901/edit

To same pro google analytics

**Comment by Halama** [comment]
Zatím jsem to zařízl na straně papertrailu tím že jsem té log destination zakázal registraci nových systémů.
![image](https://user-images.githubusercontent.com/903531/36072080-8844c2ae-0f19-11e8-9b50-53e0d582b838.png)

**Comment by odinuv** [comment]
ma to jit pres docker runner

**Comment by Halama** [comment]
ten debug logy pro autora komponenty zatim neumi ne?

**Comment by odinuv** [comment]
umi https://developers.keboola.com/extend/common-interface/logging/#gelf-logger

**Comment by MiroCillik** [comment]
@odinuv a ten GELF posiela tie "internall" logy do toho Greylog2 serveru? A ten mame niekde alebo si ho musim sam spojzadnit plz?

**Comment by odinuv** [comment]
server = docker runner, nemusis nic zprovoznovat

**Comment by MiroCillik** [comment]
Solved in https://github.com/keboola/google-sheets-writer/pull/14
