### ISSUE TITLE
Dont truncate sheet

### ISSUE THREAD

**Issue by MiroCillik** [keboola/google-sheets-writer#11]
Aktuálně smažeme při loadu dat celý sheet, resizneme ho na 1:1 a znovu do něj zapíšeme. Díky tomu se jebne všechno, co je kolem postavené (druhý sheet s grafem, odkazama na raw data, atd.)

Miro říkal, že to byl nějaký workaround. Tak pokud to není stále nutné, tak bych to zkusil zrušit.

**Comment by padak** [comment]
(PB https://keboola.productboard.com/feature-board/6271-planning/features/818362)

**Comment by ujovlado** [comment]
Toto sme revertli

**Comment by MiroCillik** [comment]
Tu je to spravene lespie https://github.com/keboola/google-sheets-writer/pull/17
