### ISSUE TITLE
special characters in file/sheet name

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-sheets-writer#13]
Vytvořil jsem sheet s názvem `Users > Users Users 300+ / Users > Users Users 300+` a v něm list `Users > Users Users 300+ / Users > Users Users 300+` a dostávám tuhle chybu

---

Client error: 
`POST https://sheets.googleapis.com/v4/spreadsheets/1A_0AxZuF8XrKW0Mnc7C_MZtYBhck0cKPH1nPcA98ZF0/values/Users%20%3E%20Users%20Users%20300+%20/%20Users%20%3E%20Users%20Users%20300+:clear` 
resulted in a `404 Not Found` response:

---

Vypadá to na špatně escapované `+`. Zajímavý je, že to ten sheet vytvoří správně, ale pak už to do něj nezapíše.

**Comment by ondrejhlavacek** [comment]
https://keboola.zendesk.com/agent/tickets/8146

**Comment by ondrejhlavacek** [comment]
K hraní na https://connection.keboola.com/admin/projects/232/writers/keboola.wr-google-sheets/371982325

**Comment by MiroCillik** [comment]
Fixed in https://github.com/keboola/google-sheets-writer/commit/42d73bde76de292fbc5aeca23cafa59442c97dd9
