### ISSUE TITLE
Problem with larger tables

### ISSUE THREAD

**Issue by ujovlado** [keboola/google-sheets-writer#15]
Look like there's a problem with larger sheets (~150k rows), since there's document metadata update every 1000 rows.

Is there a way how to tune it?

In previous version (1.2.1) same configuration took 4-5 minutes. In current version it timed out.

**Comment by ujovlado** [comment]
https://keboola.zendesk.com/agent/tickets/8190

**Comment by padak** [comment]
Mě tady https://connection.keboola.com/admin/projects/2117/jobs/380482277?q=%2Bparams.component%3Akeboola.wr-google-sheets%20%2Bparams.config%3A372058201 jede load 18k řádku 3/4 hodiny #fyi

**Comment by ujovlado** [comment]
Related to #16

**Comment by MiroCillik** [comment]
FIXED in https://github.com/keboola/google-sheets-writer/pull/17
