### ISSUE TITLE
error Requested writing within range ['COM: Problem items'!A1]

### ISSUE THREAD

**Issue by kacurez** [keboola/google-sheets-writer#23]
viac infa https://keboola.slack.com/archives/C0MGF8TCY/p1526564939000302

**Comment by MiroCillik** [comment]
Je to bug v metode Append v Google Sheets API https://issuetracker.google.com/issues/36761154

**Comment by MiroCillik** [comment]
A vyskytlo sa to teraz preto, ze aj pri update sme od 1.3.1 zacali pouzivat metodu append:
https://github.com/keboola/google-sheets-writer/blob/master/src/Keboola/GoogleSheetsWriter/Sheet.php#L96

**Comment by MiroCillik** [comment]
Fixed in https://github.com/keboola/google-sheets-writer/releases/tag/1.3.4
