### ISSUE TITLE
RestApi::decideRetry() must implement interface ResponseInterface, null given

### ISSUE THREAD

**Issue by natocTo** [keboola/google-sheets-writer#43]
https://keboola.slack.com/archives/C09U3R1J4/p1556518419064000

**Comment by kacurez** [comment]
again https://keboola.slack.com/archives/C09U3R1J4/p1557422493101400

TypeError:Argument 3 passed to Keboola\\Google\\ClientBundle\\Google\\RestApi::decideRetry() must implement interface Psr\\Http\\Message\\ResponseInterface, null given, called in \/code\/vendor\/keboola\/google-client-bundle\/Keboola\/Google\/ClientBundle\/Google\/RestApi.php on line 67

**Comment by ondrejhlavacek** [comment]
a zas https://keboola.slack.com/archives/C09U3R1J4/p1560729931002700

**Comment by Halama** [comment]
Dnes opět https://keboola.slack.com/archives/C09U3R1J4/p1562787047000300
