### ISSUE TITLE
TypeError:Argument 3 passed to Keboola\Google\ClientBundle\Google\RestApi::decideRetry() must implement interface Psr\Http\Message\ResponseInterface, null given

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-sheets-writer#45]
called in /code/vendor/keboola/google-client-bundle/Keboola/Google/ClientBundle/Google/RestApi.php on line 67

https://connection.keboola.com/admin/utils/logs?file=2019/06/17/03/2019-06-17-03-48-50-5d06f18287372-exception

https://connection.keboola.com/admin/utils/logs?file=2019/06/17/03/2019-06-17-03-48-50-5d06f1828e0f3-log

**Comment by Halama** [comment]
Házelo teď při síťových problémech v AWS https://github.com/keboola/devops/issues/128

![image](https://user-images.githubusercontent.com/903531/64149883-6bd9e800-ce27-11e9-8b70-34dcd90556da.png)
