### ISSUE TITLE
TypeError:Argument 3 passed to Keboola\Google\ClientBundle\Google\RestApi::decideRetry() must implement interface Psr\Http\Message\ResponseInterface

### ISSUE THREAD

**Issue by pivnicek** [keboola/google-sheets-writer#47]
https://connection.keboola.com/admin/utils/logs?file=2019/10/01/02/2019-10-01-02-33-27-5d929ed77d5b3-exception

**Comment by Halama** [comment]
Další https://keboola.slack.com/archives/C09U3R1J4/p1572568807006200
