### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Halama** [keboola/google-sheets-writer#5]
Tohle by nemuselo logovat:
![image](https://user-images.githubusercontent.com/903531/33272029-384abda6-d389-11e7-8074-89abed999ff2.png)

Naopak by to mohlo říkat co zapisuje a v jakém režimu.

**Comment by kacurez** [comment]
+1
prave som chcel zareportovat to iste - je tam malo infa, navyse to matie uzivatelov kedze sa do kontajneru vyexportuju aj disabled tabulky
