### ISSUE TITLE
Append mode overwrite

### ISSUE THREAD

**Issue by Halama** [keboola/google-sheets-writer#6]
Vypadá to že append režim se zastaví u druhého řádku a od nějk přepisuje.
Tady je testovací orchestrace https://connection.keboola.com/admin/projects/236/orchestrations/333259504 která transformací vygeneruje tabulku s jendím řádkem na kterém je aktuální timestamp a pak to pošle jako append na google drive sheets.

![image](https://user-images.githubusercontent.com/903531/33286679-6bbe6fca-d3b6-11e7-98fa-cbc48583f0ad.png)

**Comment by MiroCillik** [comment]
Fixed in https://github.com/keboola/google-sheets-writer/commit/f8f2bc928c382914a2d5680a6b03743c42de448d
