### ISSUE TITLE
Missing retry?

### ISSUE THREAD

**Issue by odinuv** [keboola/google-sheets-writer#7]
"errorOutput": "[2017-12-26 01:12:48] wr-google-sheets.ERROR: Server error: `POST https:\/\/www.googleapis.com\/oauth2\/v4\/token` resulted in a `502 Bad Gateway` response:        \\n\\n  \\n  \\n  

Application error: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.wr-google-sheets:1.1.3 container '341374427-341366465.341374429--0-keboola-wr-google-sheets' failed: (2) [2017-12-26 01:12:48] wr-google-sheets.ERROR: Server error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a ` ... temporary error and could not complete your request.<p>Please try again in 30 seconds. <ins>That’s all we know.</ins>\n"} []

https://keboola.slack.com/archives/C09U3R1J4/p1514247246000040

**Comment by MiroCillik** [comment]
Toto je uz chyba, ktoru to vypluje potom co vycerpa pocet retries, aspon by to tak malo byt, pri 5xx to robi vzdy retry.

**Comment by odinuv** [comment]
no tak jestli je to fakt docasnej error, tak by to melo asi skoncit user errorem?

**Comment by MiroCillik** [comment]
To by asi melo

**Comment by MiroCillik** [comment]
Fixed in https://github.com/keboola/google-sheets-writer/commit/afb30b8e8b5be4ccbb35d0475e705d303d7d41d9
